### ISSUE TITLE
LPHostEnvironment' is not a member type of 'LPABCSDK'

### ISSUE THREAD

**Issue by ailtonvivaz** [LivePersonInc/lpabcsdk#1]
When I was migrating the project to Swift 5.1, this error occurred.
All erros shown are in `x86_64-apple-ios-simulator.swiftinterface` file.

However, I found in the Apple Developer Forums this thread:
https://forums.developer.apple.com/thread/123253

<img width="1525" alt="Print Error" src="https://user-images.githubusercontent.com/12598328/68772694-fb123180-0608-11ea-9f42-328b5db1476d.png">

**Comment by omerberger** [comment]
Thanks, I updated building using latest Xcode 11.2.1 (11B53) and looks like the issue got resolved.
I'll surely keep an eye for modules mismatched.

**Comment by ailtonvivaz** [comment]
Thanks for fix this error. Now I could build with the framework in the Podfile.
However, one callback used not is working.
`Value of type 'LPABCSDK' has no member 'implicitEventClosure'`

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/12598328/68858926-f01cd700-06c4-11ea-83f1-258de3faefd6.png">

**Comment by omerberger** [comment]
it is all under `abcEventCallback`, updated readme.

**Comment by ailtonvivaz** [comment]
The `acbEventCallback` requires a callback of type `((LPABCSDK.LPABCEvent, URLQueryItem?) -> Void)?`.
Thus, I needed to use the below code to work:
```
lpabcsdk.abcEventCallback = { [weak self] implicitType, _ in

    guard let self = self else {return}
    
    if implicitType == .newConversation {
        self.sendSDE()
    }
    
}
```
