### ISSUE TITLE
LPHostEnvironment' is not a member type of 'LPABCSDK'

### ISSUE THREAD

**Issue by ailtonvivaz** [LivePersonInc/lpabcsdk#2]
I updated my project to use Xcode 11.4 and it is giving an error in the library. Probably because the compiled version does not support.

How can I solve this?

**Comment by luandrecast-lp** [comment]
@ailtonvivaz please check with the latest releases - we now have support for Xcode 11.4.1 up to 11.6
https://github.com/LivePersonInc/lpabcsdk/releases
